name: Publish
on:
  push:
    branches: ['feat/deploy']
# on:
#   workflow_dispatch:

jobs: # Задания
  env: # определение env переменных
    name: add env
    runs-on: ubuntu-latest
    env:
      REACT_APP_NODE_ENV: ${{ secrets.REACT_APP_NODE_ENV }}
      REACT_APP_PUBLIC_URL: ${{ secrets.REACT_APP_PUBLIC_URL }}
      REACT_APP_DEV_URL: ${{ secrets.REACT_APP_DEV_URL }}

  publish: # Опубликовать
    name: Build and Publish
    # needs: test # Запускать только если тест прошёл успешно
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build
      - run:

      - name: Copy build to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: build/
          target: /var/www/ecabinet

      # - name: Set environment variables on server
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.HOST }}
      #     port: ${{ secrets.PORT }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       cd /var/www/ecabinet
      #       rm -rf .env
      #       echo REACT_APP_NODE_ENV=${{ secrets.REACT_APP_NODE_ENV }}  >> .env
      #       echo REACT_APP_PUBLIC_URL=${{ secrets.REACT_APP_PUBLIC_URL }}  >> .env
      #       echo REACT_APP_DEV_URL=${{ secrets.REACT_APP_DEV_URL }}  >> .env

      - name: Restart nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: echo ${{ secrets.PASSWORD }} | sudo -S nginx -s reload
